<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm2.aspx.cs" Inherits="Simple.ModelBindingSortAndPaging.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="GridView1" runat="server"
                SelectMethod="GetAllAccounts"
                UpdateMethod="UpdateAccount"
                DeleteMethod="DeleteAccount"
                AutoGenerateDeleteButton="true"
                AutoGenerateEditButton="true"
                ItemType="Simple.ModelBindingSortAndPaging.Models.Account"
                AllowPaging="True"
                AllowSorting="True"
                DataKeyNames="UserId"
                PageSize="2">
            </asp:GridView>
            <asp:DetailsView ID="DetailsView1" runat="server" Height="50px" Width="125px"
                ItemType="Simple.ModelBindingSortAndPaging.Models.Account"
                DefaultMode="Insert"
                SelectMethod="GetAllAccounts"
                InsertMethod="InsertAccount"
                GridLines="None">
                <Fields>
                    <asp:CommandField ShowInsertButton="True" ShowCancelButton="False"
                        ButtonType="Button" />
                </Fields>
            </asp:DetailsView>
        </div>
    </form>
</body>
</html>